
export const FETCH_NEWS_LIST = 'FETCH_NEWS_LIST';
export const PRE_LOADING = 'PRE_LOADING';



export const FETCH_CATEGORY_LIST = 'FETCH_CATEGORY_LIST';



export const  START_REQUEST='START_REQUEST';
export const  RESET_REQUEST='RESET_REQUEST';
export const  FINISH_REQUEST='FINISH_REQUEST';
export const  ENABLE_REQUEST='ENABLE_REQUEST';
export const  DISABLE_REQUEST='DISABLE_REQUEST';

